port: :8090
mysql: root:xxxxxxx@tcp(xxxxxxx:xxxxxxx)/chess_card?charset=utf8mb4&parseTime=True&loc=Local&
redis:
  addr: xxxxxxx:xxxxxxx
  passwd: "xxxxxxx"
  db: 0
mongodb:
  addr: "mongodb://root:xxxxxxx@xxxxxxx:xxxxxxx/?authMechanism=SCRAM-SHA-1"

log:
  apiLogPath: src/log/
  apiLogFile: apiLog.log
  sysLogPath: src/log/
  sysLogFile: sysLog.log
